spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/book_social_network_db
#    url: jdbc:postgresql://host.docker.internal:5432/book_social_network_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: nidaan
    password: nidaan
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

server:
  port: 8088

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

#logging:
#  level:
#    org.springframework.boot.autoconfigure.jdbc: DEBUG
#    org.springframework.jdbc.core: DEBUG
#    com.zaxxer.hikari: DEBUG
#    org.hibernate: DEBUG