version: '3.8'

services:
  postgres-sql-bsn:
    image: postgres:15
    container_name: postgres-sql-bsn
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=book_social_network_db
    ports:
      - "15432:5432"
    networks:
      - bookstore-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d book_social_network_db"]  # ← FIXED THIS LINE
      interval: 30s
      timeout: 10s
      retries: 3

  pgadmin:
    container_name: pgadmin-bsn
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@booksocial.net
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "9090:80"
    networks:
      - bookstore-network
    restart: unless-stopped
    depends_on:
      - postgres-sql-bsn

  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - bookstore-network
    restart: unless-stopped

networks:
  bookstore-network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data: